### ISSUE TITLE
Question about bias

### ISSUE THREAD

**Issue by chojw** [GeraldHan/GGE#2]
Hi, 

I was just wondering, what exactly is "b" from the dataset, or entry["bias"]?

Are these the question types? I found that they are the shape of answer labels and I don't understand why they are in that shape.

Thanks in advance!

**Comment by GeraldHan** [comment]
b is the distribution bias, which is the answer distribution under certain question types through the whole dataset.  The details can be found in our paper, Sec.C in supp, and the get_bias function in main.py.

**Comment by chojw** [comment]
Got it thanks!
