### ISSUE TITLE
论文问题咨询

### ISSUE THREAD

**Issue by SakerLiu** [GeraldHan/GGE#4]
您好，你在table.1中的实验数据都是在test上进行的么，是自己复现了一遍还是从原论文中cite的呢，谢谢

**Comment by GeraldHan** [comment]
你好，这些数据都是在val set的结果。是我自己复现的

**Comment by SakerLiu** [comment]
![image](https://user-images.githubusercontent.com/30914380/141127361-56ae31ce-b397-44a8-9c06-ac9433284b53.png)
在VQA2上的差距这么d大么，还是参数设置的问题？

**Comment by GeraldHan** [comment]
是按照offical release代码https://github.com/yanxinzju/CSS-VQA复现的结果。但是论文提供的特征没有坐标信息，为了可视化和与需要额外标注的方法（HINT SCR）公平比较，我们改成了论文https://github.com/erobic/negative_analysis_of_grounding提供的特征和HAT标注。也就是说除了用的特征和HAT标注不同，其他的部分应该都是和原论文公开代码一致的。

实验结果来看，复现得到的VQA-CP结果差别不大，我们是取了多次实验的均值。但是VQA v2上面复现的结果确实有比较大差距。我们table 1实验的所有的代码都是公开的，CSS这篇文章也是开源的，您可以自己复现一下。

**Comment by SakerLiu** [comment]
嗯嗯，多谢您的回复，不知道方不方便加一下好友，交流一下这个方面的问题呢


| |
Shandong University
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月10日 ***@***.***> 写道：

是按照offical release代码https://github.com/yanxinzju/CSS-VQA复现的结果。但是论文提供的特征没有坐标信息，为了可视化和与需要额外标注的方法（HINT SCR）公平比较，我们改成了论文https://github.com/erobic/negative_analysis_of_grounding提供的特征和HAT标注。也就是说除了用的特征和HAT标注不同，其他的部分应该都是和原论文公开代码一致的。

实验结果来看，复现得到的VQA-CP结果差别不大，我们是取了多次实验的均值。但是VQA v2上面复现的结果确实有比较大差距。我们table 1实验的所有的代码都是公开的，CSS这篇文章也是开源的，您可以自己复现一下。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Shj451148969** [comment]
> 嗯嗯，多谢您的回复，不知道方不方便加一下好友，交流一下这个方面的问题呢 | | Shandong University | | ***@***.*** | 签名由网易邮箱大师定制 在2021年11月10日 ***@***.***> 写道： 是按照offical release代码[https://github.com/yanxinzju/CSS-VQA复现的结果。但是论文提供的特征没有坐标信息，为了可视化和与需要额外标注的方法（HINT](https://github.com/yanxinzju/CSS-VQA%E5%A4%8D%E7%8E%B0%E7%9A%84%E7%BB%93%E6%9E%9C%E3%80%82%E4%BD%86%E6%98%AF%E8%AE%BA%E6%96%87%E6%8F%90%E4%BE%9B%E7%9A%84%E7%89%B9%E5%BE%81%E6%B2%A1%E6%9C%89%E5%9D%90%E6%A0%87%E4%BF%A1%E6%81%AF%EF%BC%8C%E4%B8%BA%E4%BA%86%E5%8F%AF%E8%A7%86%E5%8C%96%E5%92%8C%E4%B8%8E%E9%9C%80%E8%A6%81%E9%A2%9D%E5%A4%96%E6%A0%87%E6%B3%A8%E7%9A%84%E6%96%B9%E6%B3%95%EF%BC%88HINT) SCR）公平比较，我们改成了论文[https://github.com/erobic/negative_analysis_of_grounding提供的特征和HAT标注。也就是说除了用的特征和HAT标注不同，其他的部分应该都是和原论文公开代码一致的。](https://github.com/erobic/negative_analysis_of_grounding%E6%8F%90%E4%BE%9B%E7%9A%84%E7%89%B9%E5%BE%81%E5%92%8CHAT%E6%A0%87%E6%B3%A8%E3%80%82%E4%B9%9F%E5%B0%B1%E6%98%AF%E8%AF%B4%E9%99%A4%E4%BA%86%E7%94%A8%E7%9A%84%E7%89%B9%E5%BE%81%E5%92%8CHAT%E6%A0%87%E6%B3%A8%E4%B8%8D%E5%90%8C%EF%BC%8C%E5%85%B6%E4%BB%96%E7%9A%84%E9%83%A8%E5%88%86%E5%BA%94%E8%AF%A5%E9%83%BD%E6%98%AF%E5%92%8C%E5%8E%9F%E8%AE%BA%E6%96%87%E5%85%AC%E5%BC%80%E4%BB%A3%E7%A0%81%E4%B8%80%E8%87%B4%E7%9A%84%E3%80%82) 实验结果来看，复现得到的VQA-CP结果差别不大，我们是取了多次实验的均值。但是VQA v2上面复现的结果确实有比较大差距。我们table 1实验的所有的代码都是公开的，CSS这篇文章也是开源的，您可以自己复现一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

兄弟，方便留个联系方式吗，我是一个刚入门NLP的菜鸟，想很探讨一下有关问题

**Comment by GeraldHan** [comment]
可以的，我的微信号是hxz19940815。不过我主要关注的是跨模态和cv方向的研究，对npl涉猎比较初级。



| |
韩歆哲
学生
|
|
中国科学院大学
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月13日 19:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [GeraldHan/GGE] 论文问题咨询 (Issue #4) |

嗯嗯，多谢您的回复，不知道方不方便加一下好友，交流一下这个方面的问题呢 | | Shandong University | | @.*** | 签名由网易邮箱大师定制 在2021年11月10日 @.***> 写道： 是按照offical release代码https://github.com/yanxinzju/CSS-VQA复现的结果。但是论文提供的特征没有坐标信息，为了可视化和与需要额外标注的方法（HINT SCR）公平比较，我们改成了论文https://github.com/erobic/negative_analysis_of_grounding提供的特征和HAT标注。也就是说除了用的特征和HAT标注不同，其他的部分应该都是和原论文公开代码一致的。 实验结果来看，复现得到的VQA-CP结果差别不大，我们是取了多次实验的均值。但是VQA v2上面复现的结果确实有比较大差距。我们table 1实验的所有的代码都是公开的，CSS这篇文章也是开源的，您可以自己复现一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

兄弟，方便留个联系方式吗，我是一个刚入门NLP的菜鸟，想很探讨一下有关问题

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SakerLiu** [comment]
哦哦，我是目前做NLP相关的，下一步打算做VQA相关的，感觉这一块是不是卷的也挺厉害的

从 Windows 版邮件发送

发件人: GeraldHan
发送时间: 2021年11月13日 23:01
收件人: GeraldHan/GGE
抄送: SakerLiu; Author
主题: Re: [GeraldHan/GGE] 论文问题咨询 (Issue #4)

可以的，我的微信号是hxz19940815。不过我主要关注的是跨模态和cv方向的研究，对npl涉猎比较初级。



| |
韩歆哲
学生
|
|
中国科学院大学
***@***.***
|
发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月13日 19:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [GeraldHan/GGE] 论文问题咨询 (Issue #4) |

嗯嗯，多谢您的回复，不知道方不方便加一下好友，交流一下这个方面的问题呢 | | Shandong University | | @.*** | 签名由网易邮箱大师定制 在2021年11月10日 @.***> 写道： 是按照offical release代码https://github.com/yanxinzju/CSS-VQA复现的结果。但是论文提供的特征没有坐标信息，为了可视化和与需要额外标注的方法（HINT SCR）公平比较，我们改成了论文https://github.com/erobic/negative_analysis_of_grounding提供的特征和HAT标注。也就是说除了用的特征和HAT标注不同，其他的部分应该都是和原论文公开代码一致的。 实验结果来看，复现得到的VQA-CP结果差别不大，我们是取了多次实验的均值。但是VQA v2上面复现的结果确实有比较大差距。我们table 1实验的所有的代码都是公开的，CSS这篇文章也是开源的，您可以自己复现一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

兄弟，方便留个联系方式吗，我是一个刚入门NLP的菜鸟，想很探讨一下有关问题

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Shj451148969** [comment]
@SakerLiu 兄弟，我发现你关注的内容和我比较相似，可以加个联系方式吗

**Comment by SakerLiu** [comment]
@Shj451148969 当然可以，这个结果我用RTX titian可以复现，但是在30系列结构的显卡上可能效果略差。我的邮箱是SakerLiuJin@163.com

**Comment by SakerLiu** [comment]
最近新调试了一下，3090也可以达到很好的
<img width="376" alt="微信图片_20211117101505" src="https://user-images.githubusercontent.com/30914380/142096877-d5a012ff-2286-49a8-811e-1cc798ac15df.png">
效果

**Comment by attackon1point6** [comment]
> ![image](https://user-images.githubusercontent.com/30914380/141127361-56ae31ce-b397-44a8-9c06-ac9433284b53.png) 在VQA2上的差距这么d大么，还是参数设置的问题？

您好，请问这个表格是您自己的复现结果吗？我发现自己复现的RUBi这个baseline效果和您表格差不多，但在v2 val上达不到RUBi或GGE原文，性能也是50出头，差距还有点大，方便问下后续您是如何提升v2性能的吗
